[source]
git = "https://gitlab.redox-os.org/redox-os/bootloader.git"

[build]
template = "custom"
script = """
ARCH="$(echo "${TARGET}" | cut -d - -f1)"
nasm \
    -f bin \
    -o "${COOKBOOK_STAGE}/bootloader" \
    -D "ARCH_${ARCH}" \
    -i"${COOKBOOK_SOURCE}/${ARCH}/" \
    "${COOKBOOK_SOURCE}/${ARCH}/disk.asm"
"""
